### ISSUE TITLE
Remove .bin from pattern

### ISSUE THREAD

**Issue by git-jiby-me** [KyleRoss/modclean#4]
Please remove .bin from patterns, a lot of projects use the .bin created by npm from local module binaries for different npm scripts, examples being running tests with jasmine, linters like jshint, jscs.

**Comment by KyleRoss** [comment]
Good catch, that's actually a bug since .bin is repeated in the "danger" patterns. I will remove it from the safe patterns at some point today and will let you know. Thanks for reporting!

**Comment by git-jiby-me** [comment]
Thanks !

**Comment by git-jiby-me** [comment]
Any updates on this, it also maybe makes sense to verify all the symlinks in .bin and delete the invalid ones, because if you have done `npm dedupe` earlier it leaves the invalid symlinks in .bin, which can be safely deleted.

**Comment by KyleRoss** [comment]
Sorry it took so long (just bought a house and moved). This has been fixed and published to NPM as version 1.2.3.
