### ISSUE TITLE
Removed module uglify-save-license

### ISSUE THREAD

**Issue by yoeran** [KyleRoss/modclean#8]
I ran into a problem running my Gulp scripts after using `modclean -n safe`. This is because the patterns.json has `*license*` under the safe patterns. My current Gulp flow however includes uglify and also a module called `uglify-save-license`.

Now my Gulp task breaks with the error `Error: Cannot find module 'uglify-save-license'`.
Might be a difficult thing to solve since license files never have an extension.

What would you recommend? Should this be in the patterns.json or is it possible to add an exception via the CLI? (haven't found it in the docs).

**Comment by KyleRoss** [comment]
I'm working on adding a way to ignore certain files per issue #7 but we definitely need to get this fixed as soon as possible. I will be looking into a solution and let you know what I come up with.

**Comment by DanielSundberg** [comment]
In my project "repo validate-npm-package-license" and "history" is removed, which breaks my build.

**Comment by DanielSundberg** [comment]
Command line

**Comment by TomSeldon** [comment]
Having similar issues where modules with names containing the word "license" are being removed.

e.g.

* validate-npm-package-license
* spdx-license-ids

Worked around it by not using the CLI and using it programmatically instead, but would be good to see this addressed as part of the CLI.

**Comment by KyleRoss** [comment]
Sorry for the delay, but I've added a `--ignore` option that takes a comma-separated list of glob patterns to ignore.

Example:
`modeclean --ignore="validate-npm-package-license,spdx-license-ids,history"`

Hopefully this fixes what you need. I will refactor everything in the future. This has been released to NPM as version 1.3.0
